# Generated by Django 5.0.1 on 2024-02-14 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartOrServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
            ],
            options={
                'verbose_name': 'tipo peça ou serviço',
                'verbose_name_plural': 'tipos peças ou serviços',
                'db_table': 'part_or_service_type',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='Numero')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
            ],
            options={
                'verbose_name': 'ordem de serviço',
                'verbose_name_plural': 'ordens de serviços',
                'db_table': 'service_order',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Carro')),
                ('plate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Placa')),
                ('kms', models.IntegerField(blank=True, null=True, verbose_name='KMs')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
            ],
            options={
                'verbose_name': 'veiculo',
                'verbose_name_plural': 'veiculos',
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='PartOrService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('part_or_service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_order.partorservicetype', verbose_name='Tipo')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_order.serviceorder', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'peça ou serviço',
                'verbose_name_plural': 'peças ou serviços',
                'db_table': 'part_or_service',
            },
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_order.vehicle', verbose_name='veiculo'),
        ),
    ]
